name: Docker Compose Deployment (SSH)
author: 'humbertocrispim'
branding:
  icon: server
  color: purple
description: SSH into host and deploy repository with Docker-Compose
inputs:
  ssh_private_key:
    description: Private SSH key used for logging into remote system.
    required: true
  ssh_host:
    description: Remote host name.
    required: true
  ssh_port:
    description: Remote SSH port.
    default: '22'
    required: true
  ssh_user:
    description: Remote user name.
    required: true
  docker_compose_prefix:
    description: Prefix for docker-compose containers.
    required: true
  docker_compose_filename:
    description: Docker compose file to use
    default: docker-compose.yml
  pull:
    description: Docker Compose pull images.
    default: 'false'
  registry_login:
    description: Docker registry credentials
    default: ''
  registry_secret:
    description: Docker registry credentials
    default: ''
  registry:
    description: Docker registry credentials
    default: 'ghcr.io'
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    PULL: ${{ inputs.pull }}
    REGISTRY_LOGIN: ${{ inputs.registry_login }}
    REGISTRY_SECRET: ${{ inputs.registry_secret }}
    REGISTRY: ${{ inputs.registry }}