name: Docker Compose Deployment (SSH)
author: 'nuclearpolygon'
branding:
  icon: server
  color: purple
description: SSH into host and deploy repository with Docker-Compose
inputs:
  ssh_private_key:
    description: Private SSH key used for logging into remote system.
    required: true
  ssh_host:
    description: Remote host name.
    required: true
  ssh_port:
    description: Remote SSH port.
    default: '22'
    required: false
  ssh_user:
    description: Remote user name.
    required: true
  script:
    description: Bash script to execute with remote Docker context.
    required: true
  registry_login:
    description: Docker registry credentials
  registry_secret:
    description: Docker registry credentials
  registry:
    description: Docker registry credentials
    default: 'ghcr.io'
runs:
  using: docker
  image: docker://ghcr.io/nuclearpolygon/ssh-docker-compose-action:v1
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    SCRIPT: ${{ inputs.script }}
    REGISTRY_LOGIN: ${{ inputs.registry_login }}
    REGISTRY_SECRET: ${{ inputs.registry_secret }}
    REGISTRY: ${{ inputs.registry }}